### ISSUE TITLE
Configuring Sentry.io

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-operation#28]
**Tasks**

- [x] Create an account on sentry.io
- [x] Create a team i.e. TogetherCrew
- [x] Add team members by email (mine is development.rooted@gmail.com)
- [x] Create projects (see table below).

**Projects**

| project name | platform |
| --- | --- |
| tc-uiComms | next.js |
| tc-serverComms | express |
| tc-DAOlytics | python |
| tc-botComms | node.js |

Once that is done, if I am on the team, I should be able to manage the rest.

Pricing:
- https://sentry.io/pricing/ 
- We can start with ** Developer** (free). Although they aren't clear on having multiple members.
- We may need to upgrade to **Team** at some point ($26/mo).

**Comment by daniel-ospina** [comment]
done. Added @cyri113 as Manager
