### ISSUE TITLE
Create organisation account on NPM.

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-operation#34]
In order to publish packages, we should create an organisation on npmjs.org

## Tasks

- [ ] Create account
- [ ] Create organisation
- [ ] Invite team members

## Team Members
- [ ] cr3a1
- [ ] scientists.twin@gmail.com
- [ ] behzad-rabiei [behzad.rabiei.77@gmail.com]

## Documentation

- https://docs.npmjs.com/organizations

**Comment by scientiststwin** [comment]
email: scientists.twin@gmail.com

**Comment by Behzad-rabiei** [comment]
emali: behzad.rabiei.77@gmail.com
username: behzad-rabiei
