### ISSUE TITLE
Setup tc domains 

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-operation#4]
# Goal 
- Setup our domains 

# tasks
- [ ] Help with moving the domain from Godaddy to CF
- [ ] Create sub-domains
- [ ] Assign sub-domains to environments 

# Appendix
Reference conversation is [here](https://discord.com/channels/915914985140531240/1062081781672718408/1062081784633892946)

**Comment by mehrdadmms** [comment]
- app.togethercrew.com -> for prod
- dev.togethercrew.com -> for dev
- staging.togethercrew.com -> for staging
- togethercrew.com -> for the landing

**Comment by zargarzadehm** [comment]
I had a meeting with Daniel and configured cloud flare pages for the Landing and the app and discuss with Nima to fix frontend building problems.
In the following, I should setup domains for back services (dev, rc and production), for this after config Nginx and lets-encrypt (for SSL), I will add DNS records to CF.

**Comment by mehrdadmms** [comment]
# Appending to the initial work the following has been done by @zargarzadehm 
- Meeting with Daniel
- Meeting with the development team (front and back) 
- Front-end has been hosted with Cloud Flare (both prod and dev)
- Domain has been created and set for landing, backend and dev for both prod and dev 
- Nginx has been setup 
- SSL has been setup 
**Hence, the task has been upgraded to the next level of difficulty**
